// Code generated by protoc-gen-go.
// source: log_api.proto
// DO NOT EDIT!

/*
Package log_api is a generated protocol buffer package.

It is generated from these files:
	log_api.proto

It has these top-level messages:
	Log
	LogGroup
	LogGroupList
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type Log struct {
	Time             *uint32        `protobuf:"varint,1,req,name=time" json:"time,omitempty"`
	Contents         []*Log_Content `protobuf:"bytes,2,rep,name=contents" json:"contents,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *Log) Reset()                    { *m = Log{} }
func (m *Log) String() string            { return proto.CompactTextString(m) }
func (*Log) ProtoMessage()               {}
func (*Log) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Log) GetTime() uint32 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

func (m *Log) GetContents() []*Log_Content {
	if m != nil {
		return m.Contents
	}
	return nil
}

type Log_Content struct {
	Key              *string `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Value            *string `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Log_Content) Reset()                    { *m = Log_Content{} }
func (m *Log_Content) String() string            { return proto.CompactTextString(m) }
func (*Log_Content) ProtoMessage()               {}
func (*Log_Content) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *Log_Content) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *Log_Content) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

type LogGroup struct {
	Logs             []*Log  `protobuf:"bytes,1,rep,name=logs" json:"logs,omitempty"`
	Reserved         *string `protobuf:"bytes,2,opt,name=reserved" json:"reserved,omitempty"`
	Topic            *string `protobuf:"bytes,3,opt,name=topic" json:"topic,omitempty"`
	Source           *string `protobuf:"bytes,4,opt,name=source" json:"source,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LogGroup) Reset()                    { *m = LogGroup{} }
func (m *LogGroup) String() string            { return proto.CompactTextString(m) }
func (*LogGroup) ProtoMessage()               {}
func (*LogGroup) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LogGroup) GetLogs() []*Log {
	if m != nil {
		return m.Logs
	}
	return nil
}

func (m *LogGroup) GetReserved() string {
	if m != nil && m.Reserved != nil {
		return *m.Reserved
	}
	return ""
}

func (m *LogGroup) GetTopic() string {
	if m != nil && m.Topic != nil {
		return *m.Topic
	}
	return ""
}

func (m *LogGroup) GetSource() string {
	if m != nil && m.Source != nil {
		return *m.Source
	}
	return ""
}

type LogGroupList struct {
	LogGroupList     []*LogGroup `protobuf:"bytes,1,rep,name=logGroupList" json:"logGroupList,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *LogGroupList) Reset()                    { *m = LogGroupList{} }
func (m *LogGroupList) String() string            { return proto.CompactTextString(m) }
func (*LogGroupList) ProtoMessage()               {}
func (*LogGroupList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *LogGroupList) GetLogGroupList() []*LogGroup {
	if m != nil {
		return m.LogGroupList
	}
	return nil
}

func init() {
	proto.RegisterType((*Log)(nil), "Log")
	proto.RegisterType((*Log_Content)(nil), "Log.Content")
	proto.RegisterType((*LogGroup)(nil), "LogGroup")
	proto.RegisterType((*LogGroupList)(nil), "LogGroupList")
}

var fileDescriptor0 = []byte{
	// 197 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x4c, 0x8d, 0xcd, 0x4a, 0xc5, 0x30,
	0x10, 0x46, 0xb9, 0x37, 0x51, 0x7b, 0xa7, 0xa9, 0xc8, 0xac, 0x82, 0x0b, 0x2d, 0x05, 0xa1, 0xab,
	0x08, 0xbe, 0x82, 0x0b, 0x37, 0x05, 0xf7, 0x6e, 0xa4, 0xd4, 0xa1, 0x04, 0x6b, 0x27, 0x24, 0x69,
	0xc1, 0xb7, 0x37, 0xfd, 0x03, 0x77, 0x39, 0xe1, 0x3b, 0x67, 0xa0, 0x18, 0xb8, 0xff, 0x6c, 0x9d,
	0x35, 0xce, 0x73, 0xe4, 0xea, 0x03, 0x44, 0xc3, 0x3d, 0x2a, 0x90, 0xd1, 0xfe, 0x90, 0x3e, 0x95,
	0xe7, 0xba, 0xc0, 0x07, 0xc8, 0x3a, 0x1e, 0x23, 0x8d, 0x31, 0xe8, 0x73, 0x29, 0xea, 0xfc, 0x45,
	0x99, 0xb4, 0x32, 0xaf, 0xdb, 0xe7, 0xfd, 0x13, 0xdc, 0xec, 0x4f, 0xcc, 0x41, 0x7c, 0xd3, 0xef,
	0xea, 0x5d, 0xb0, 0x80, 0xab, 0xb9, 0x1d, 0x26, 0x4a, 0x52, 0xc2, 0xea, 0x1d, 0xb2, 0x64, 0xbd,
	0x79, 0x9e, 0x1c, 0x22, 0xc8, 0x74, 0x38, 0xa4, 0xe1, 0x92, 0x93, 0x4b, 0x0e, 0xef, 0x20, 0xf3,
	0x14, 0xc8, 0xcf, 0xf4, 0x95, 0x8c, 0xd3, 0x16, 0x88, 0xec, 0x6c, 0xa7, 0xc5, 0x8a, 0xb7, 0x70,
	0x1d, 0x78, 0xf2, 0x1d, 0x69, 0xb9, 0x70, 0xf5, 0x0c, 0xea, 0x08, 0x36, 0x36, 0x44, 0x7c, 0x04,
	0x35, 0xfc, 0xe3, 0x3d, 0x7e, 0x31, 0xc7, 0xe8, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x58, 0xb8, 0x2f,
	0xd2, 0xed, 0x00, 0x00, 0x00,
}
